name: deploy

on:
  push:
    branches:
      - main
      - develop

deploy:
  runs-on: ubuntu-latest
  environment:
    name: develop
    url: https://example.com
  steps:
  - uses: actions/checkout@v2

  - name: hello world
    run: |
      echo "{{ secrets.PERIOD }} world!!"
