name: deploy-dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://example.com
    steps:
    - uses: ./.github/workflows/actions/deploy
