name: deploy-dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://example.com
    steps:
    - uses: actions/checkout@v2

    - name: hello world
      run: |
        echo "${{ secrets.PERIOD }} world!!"
