name: deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy
      with:
        period: "${{ secrets.PERIOD }}"
